### ISSUE TITLE
wicket:id attribute autocomplete

### ISSUE THREAD

**Issue by jamerlan** [minman/wicketforge#167]
Is it possible to have "wicket:id" autocomplete during typing?

What I mean:
1) open html file
2) start typing <div wi

expected from editor: wicket:id is shown as a suggestion to autocomplete. So you can type wi, popup should appear suggesting "wicket:id" and if you press enter - you have wicket:id "typed"

actual results: editor suggests other attributes and it have no idea that "wicket:id" is possible here

**Comment by minman** [comment]
I suggest to add "wicket:id" to "Unknown HTML tag attribute"-Inspection like this:

![screen](https://cloud.githubusercontent.com/assets/1247254/7239041/1c943770-e7a7-11e4-8c69-3cd69fd47c81.png)

I could provide a code completion for wicket:id but IDEA inspection would still report wicket:id as illegal attribute (because its not xhtml compliant).

Adding wicket:id to unknown HTML tag attributes automatically add this also to code completion and doesn't report it anymore as unknown. So I think this is much better.

**Comment by minman** [comment]
So give it a try and feel free to comment if it doesn't fit you needs.

**Comment by jamerlan** [comment]
Thank you!!! It works good!!!

I think its not very intuitive to new users :-) if plugin can register this custom attribute automagically - would be awesome!

**Comment by minman** [comment]
I've already looked to automatically register but unfortunately it's not possible without a ugly hack (as far as i see). I'm gonna ask jetbrians, maybe I overlooked something.
